# Generated by Django 4.2.7 on 2026-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_add_matched_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="extracted_achievements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="extracted_certificates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resume",
            name="extracted_projects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="achievement_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="certification_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="projects_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="structure_score",
            field=models.FloatField(default=0.0),
        ),
    ]
